import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const satoshiFont = localFont({
  src: [
    {
      weight: "400",
      style: "normal",
      path: "../fonts/Satoshi-Regular.otf",
    },
    {
      weight: "700",
      style: "normal",
      path: "../fonts/Satoshi-Bold.otf",
    },
    {
      weight: "400",
      style: "italic",
      path: "../fonts/Satoshi-Italic.otf",
    },
    {
      weight: "700",
      style: "italic",
      path: "../fonts/Satoshi-BoldItalic.otf",
    },
    {
      weight: "500",
      style: "normal",
      path: "../fonts/Satoshi-Medium.otf",
    },
    {
      weight: "500",
      style: "italic",
      path: "../fonts/Satoshi-MediumItalic.otf",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshiFont.className} antialiased`}>{children}</body>
    </html>
  );
}
